=== Facets-cloud/InCa/intent_types/mysql/v1alpha1/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["api_version", "metadata", "kind", "spec", "flavor"],
  "properties": {
    "api_version": {
      "type": "string",
      "enum": ["v1alpha1"],
      "description": "Specifies the version of the schema."
    },
    "metadata": {
      "type": "object",
      "required": ["name"],
      "properties": {
        "maintainer": {"type": "string"},
        "documentation_link": {"type": "string"},
        "labels": {
          "type": "object",
          "additionalProperties": {"type": "string"}
        },
        "name": {"type": "string"},
        "description": {"type": "string"}
      }
    },
    "kind": {"type": "string"},
    "spec": {
      "type": "object",
      "required": ["version", "replication"],
      "properties": {
        "version": {"type": "string"},
        "server_variables": {
          "type": "object",
          "additionalProperties": {"type": "string"},
          "description": "Optional MySQL server variables."
        },
        "replication": {
          "type": "object",
          "required": ["enabled", "type", "replica_count"],
          "properties": {
            "enabled": {"type": "boolean"},
            "type": {"type": "string"},
            "replica_count": {"type": "integer"}
          },
          "backup": {
            "type": "object",
            "description": "Optional backup configuration for mysql server.",
            "properties": {
              "enabled": {"type": "boolean", "description":"set true to enable backup"}, 
              "frequency":{"type": "number", "description":"backup frequency"}, 
              "retention": {"type": "number","description":"Number of days the data will be persistent"}
           
            }
          }
        }
      }
    },
    "disabled": {"type": "boolean", "default": false},
    "flavor": {
      "type": "object",
      "required": ["version", "name"],
      "properties": {
        "version": {"type": "string"},
        "name": {"type": "string"}
      }
    },
    "advanced": {"type": "object"}
  }
}

=== Facets-cloud/InCa/intent_types/mysql/v1alpha1/sample.json
{
  "api_version": "v1alpha1",
  "metadata": {
    "maintainer": "rohit@example.com",
    "documentation_link": "https://example.com/documentation",
    "labels": {
      "owner": "infrastructure@example.com"
    },
    "name": "my-mysql-instance",
    "description": "A MySQL database instance."
  },
  "kind": "mysql",
  "spec": {
    "version": "8.0",
    "server_variables": {
      "max_connections": "1000",
      "query_cache_size": "0"
    },
    "size": {
      "cpu": "100m",
      "memory": "100Mi",
      "volume": "50G"
    },
    "replication": {
      "enabled": true,
      "type": "master-slave",
      "replica_count": 2
    }
  },
  "disabled": false,
  "flavor": {
    "version": "1.0",
    "name": "standard"
  },
  "advanced": {
    "backup":{
      "enabled":false,
      "backup_window":"0 0 * * 7"
    }, 
    "monitoring": true
  }
}
